### ISSUE TITLE
UnboundLocalError in Install script

### ISSUE THREAD

**Issue by BeadW** [teej/titan#11]
When following the install instructions and executing the below an exception is thrown.:
```
EXECUTE IMMEDIATE
  FROM @titan.public.titan_aws/install;
```
Response from Snowflake is shown below.
Currently the project seems to not to be installable.
```
Python Interpreter Error:
Traceback (most recent call last):
  File "/home/udf/501152416749/titan-0.1.1.zip/titan/spi.py", line 72, in install
    session_ctx = dp.fetch_session(conn)
  File "/home/udf/501152416749/titan-0.1.1.zip/titan/data_provider.py", line 160, in fetch_session
    session_obj = execute(
  File "/home/udf/501152416749/titan-0.1.1.zip/titan/client.py", line 72, in execute
    return _execute(session, sql, use_role)
  File "/home/udf/501152416749/titan-0.1.1.zip/titan/client.py", line 51, in _execute
    print(f"[{session.user}:{session.role}] >", sql_text, end="")
UnboundLocalError: local variable 'session' referenced before assignment
 in function INSTALL with handler titan.spi.install
```

**Comment by teej** [comment]
Sorry I missed this, I'll get this fixed in 0.1.2
